// Generated by ChatGPT

import React from "react";

interface HeadingProps {
  children: React.ReactNode;
  className?: string;
}

const Heading: React.FC<HeadingProps> = ({ children, className = "" }) => {
  return (
    <h1
      className={`font-roboto font-light text-[64px] md:text-[50px] sm:text-[36px] leading-[64px] sm:leading-[52px] text-[#BDBDBD] ${className}`}
    >
      {children}
    </h1>
  );
};

export default Heading;
