// Generated by ChatGPT

import React from "react";

interface SubHeadingProps {
  children: React.ReactNode;
  className?: string;
}

const SubHeading: React.FC<SubHeadingProps> = ({
  children,
  className = "",
}) => {
  return (
    <h2
      className={`font-roboto font-bold text-[64px] md:text-[48px] sm:text-[48px] leading-[64px] sm:leading-[48px] text-[#0A1A44] uppercase ${className}`}
    >
      {children}
    </h2>
  );
};

export default SubHeading;
